### PR TITLE
V0.1.dev dlt

### PR DESCRIPTION
**Pull request by debthomas**
Hi, I have made quite a lot of changes, tried to address your last comments, ran jshint on the code, quite a lot of restructuring of the flow of the function, added error checking and testing. Also added a brief description of how to run it.

### CODE REVIEW

**Comment by andrewroberts** [comment]
Deb, Do you get this if I reply to the GitHub notification?

**Comment by debthomas** [comment]
Morning, Yeah I get an email for each comment you add.

**Comment by andrewroberts** [comment]
Cool. Ok thnx for this look forward to reading through  😀

**Comment by andrewroberts** [comment]
Something has gone wrong with your push - Code.gs looks like it is empty.

While you are there could you rename Code.gs to TsJournalTrello.gs. Thanks.

**Comment by debthomas** [comment]
Oh man

**Comment by andrewroberts** [comment]
I went ahead and had a look your script project:

- Indentation goes a bit wonky around lien 155 on the some(), 87 to 107 around the assert.
- getTrelloCardUrl() is a private function so it can either be defined within tsJournalTrello() or needs an underscore on the end so it does not become part of the libraries API. tsJournalTrello() should be the only method that TsJournalTrello exports
- Could you give tsJournalTrello_() a more descriptive name like linkHeaders_()
- line 130. You only need to specifically define something as null if you are going to check for null later which you don't do, you use the false returned from the some instead (orgFound). So the definition is redundant. 
- line 157 can be "if (!orgFound)"
- line 158 you will need to return or the code with continue without an org and fail later
- line 176. You want to either not mute the exceptions and use a try catch, or mute exceptions and check the response code. You've muted the exception so an error won't be ever thrown making the try/catch redundant. Although generally you want all error to purculate up to the main try/catch (line 69) so that all errors are processed the same way, i.e. don't use try/catch in the code unless you really have to.
-  line 176. Adding .json is a clever way to get the Trello board ID, however it is only going to work if the board is public, which they most often aren't. You'll need to use a similar technique to getTrelloCardUrl() where we use the private API and token.
- line 190. There will be multiple dates with Heading 1. You'll need to look for the last one.
- line 206. verbose variable names please - "paragraphs".
- line 228. This will fall through to return SUCCESS. Could you make the indentation a lot less by either returning if a condition is not met, or splitting out the code into functions; choose one technique rather than mixing the two. Whichever you choose could you label the closing braces (line 276 on) so we know where we are. 
- line 267 replace Logger.log

**Pull request closed without merging**
